{"uuid": "6ffcc652-284c-45c2-8033-7a964b014cbc", "children": ["2834f80a-ec69-427a-9408-8df7d6875057"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chromedriver.storage.googleapis.com', port=443): Max retries exceeded with url: /LATEST_RELEASE_92.0.4515 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f287e177a90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n", "trace": "  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/venv/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/tests/conftest.py\", line 21, in init_driver\n    web_driver = webdriver.Chrome(ChromeDriverManager().install())\n  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/venv/lib/python3.8/site-packages/webdriver_manager/chrome.py\", line 34, in install\n    driver_path = self._get_driver_path(self.driver)\n  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/venv/lib/python3.8/site-packages/webdriver_manager/manager.py\", line 23, in _get_driver_path\n    driver_version = driver.get_version()\n  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/venv/lib/python3.8/site-packages/webdriver_manager/driver.py\", line 43, in get_version\n    return self.get_latest_release_version()\n  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/venv/lib/python3.8/site-packages/webdriver_manager/driver.py\", line 66, in get_latest_release_version\n    resp = requests.get(f\"{self._latest_release_url}_{self.browser_version}\")\n  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/venv/lib/python3.8/site-packages/requests/api.py\", line 75, in get\n    return request('get', url, params=params, **kwargs)\n  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/venv/lib/python3.8/site-packages/requests/api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/venv/lib/python3.8/site-packages/requests/sessions.py\", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/venv/lib/python3.8/site-packages/requests/sessions.py\", line 655, in send\n    r = adapter.send(request, **kwargs)\n  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/venv/lib/python3.8/site-packages/requests/adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1627546474500, "stop": 1627546484575}], "start": 1627546474500, "stop": 1627546484781}